meta_product_name: "CookItEasy ğŸ¥"
meta_title: "Des recettes EZPZ !"
meta_description: "CookItEasy te permet de trouver des recettes simples et dÃ©licieuses mais aussi de partager les tiennes !"
meta_image: "image_meta.png" # should exist in `app/assets/images/`
